@host = http://localhost:3333

@user_id = 1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMDg0YzI0Yy1jYTRmLTRhMGMtOWIwMS1kNWI4NDBiOWVlNDUiLCJpYXQiOjE3NTI1MzkxMDh9.Xwmwu9ZQSJOdWk6kIGWFR4mdsje6_2QrTE9iuH7594c

### Health check
GET {{host}}/health

### Create a user
POST {{host}}/users
Content-Type: application/json

{
    "name": "Sonic",
    "email": "sonic20@mail.com",
    "password": "123456"
}

### Authenticate
POST {{host}}/auth
Content-Type: application/json

{
    "email": "sonic20@mail.com",
    "password": "123456"
}

### Get all users
GET {{host}}/me
Authorization: Bearer {{token}}

### Get a user by id
GET {{host}}/users/{{user_id}}

### Update a user
PUT {{host}}/users/{{user_id}}
Content-Type: application/json

### Create a gym
POST {{host}}/gyms
Content-Type: application/json

{
    "title": "Nodejs - typescript gym",
    "description": "Academia do nodejs e typescript",
    "phone": "11999999999",
    "latitude": -23.2896771,
    "longitude": -46.4831027
}

### Search gyms
GET {{host}}/gyms/search?query=Nodejs

### Search gyms by distance
GET {{host}}/gyms/nearby?latitude=-23.2896771&longitude=-46.4891027

